/* eslint-disable */
/**
 * Generated by Convex
 * Do not manually edit this file
 */

import type {
  GenericDataModel,
  GenericQueryCtx,
  GenericMutationCtx,
  GenericActionCtx,
  QueryBuilder,
  MutationBuilder,
  ActionBuilder,
  HttpActionBuilder,
} from "convex/server";
import type { GenericId } from "convex/values";

export type TableNames = "projects" | "tasks" | "comments" | "chats" | "chatMessages" | "notifications" | "events" | "signals" | "taskDependencies";

export type Document = any;

export type Id<TableName extends TableNames = TableNames> = GenericId<TableName>;

export interface DataModel extends GenericDataModel {
  projects: {
    document: Document;
    fieldPaths: string;
    indexes: { by_slug: string; by_name: string };
    searchIndexes: any;
    vectorIndexes: any;
  };
  tasks: {
    document: Document;
    fieldPaths: string;
    indexes: { by_project: string; by_status: string; by_project_status: string; by_assignee: string; by_project_position: string };
    searchIndexes: any;
    vectorIndexes: any;
  };
  comments: {
    document: Document;
    fieldPaths: string;
    indexes: { by_task: string; by_type: string };
    searchIndexes: any;
    vectorIndexes: any;
  };
  chats: {
    document: Document;
    fieldPaths: string;
    indexes: { by_project: string };
    searchIndexes: any;
    vectorIndexes: any;
  };
  chatMessages: {
    document: Document;
    fieldPaths: string;
    indexes: { by_chat: string };
    searchIndexes: any;
    vectorIndexes: any;
  };
  notifications: {
    document: Document;
    fieldPaths: string;
    indexes: { by_read: string; by_severity: string; by_created: string };
    searchIndexes: any;
    vectorIndexes: any;
  };
  events: {
    document: Document;
    fieldPaths: string;
    indexes: { by_project: string; by_task: string; by_type: string; by_created: string };
    searchIndexes: any;
    vectorIndexes: any;
  };
  signals: {
    document: Document;
    fieldPaths: string;
    indexes: { by_task: string; by_kind: string; by_blocking: string; by_responded: string; by_created: string };
    searchIndexes: any;
    vectorIndexes: any;
  };
  taskDependencies: {
    document: Document;
    fieldPaths: string;
    indexes: { by_task: string; by_depends_on: string; by_task_depends_on: string };
    searchIndexes: any;
    vectorIndexes: any;
  };
}

export type QueryCtx = GenericQueryCtx<DataModel>;
export type MutationCtx = GenericMutationCtx<DataModel>;
export type ActionCtx = GenericActionCtx<DataModel>;

export declare const query: QueryBuilder<DataModel, "public">;
export declare const mutation: MutationBuilder<DataModel, "public">;
export declare const action: ActionBuilder<DataModel, "public">;
export declare const httpAction: HttpActionBuilder;
